# Generated by Django 5.0 on 2023-12-23 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(choices=[('h', 'heads'), ('t', 'tails')], max_length=1)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
